[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.53"
anyhow = "1.0.100"
semver = "1.0.27"
toml = "0.9.8"
smallvec = "1.15.1"
