[package]
name = "caolo-disassembler"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cao-lang = { path = "../cao-lang/" }
serde_json = "1.0.145"
clap = "4.5.53"
anyhow = "1.0.100"
